app:
    resource: '@AppBundle/Controller/'
    type: annotation

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

# app/config/routing.yml
#easy_admin_bundle:
#    resource: "@EasyAdminBundle/Controller/AdminController.php"
#    type:     annotation
#    prefix:   /_secret_backend  # <-- change this value

